---
- name: Install KVM
  ansible.builtin.package:
    name:
      - bridge-utils
      - cpu-checker
      - libvirt-clients
      - libvirt-daemon
      - qemu
      - qemu-kvm
      - virtinst
      - qemu-kvm
      - libvirt-daemon-system
    state: present

- name: Start libvirt
  ansible.builtin.service:
    name: libvirtd
    enabled: yes
    state: restarted
