---
# Basic setup for k8s
- include_tasks: setup.yaml

# Install k8s
- include_tasks: "{{ 'main_' + (ansible_distribution | lower) +'.yaml' }}"

# Prepare k8s
- name: Create ~/.kube
  ansible.builtin.file:
    path: ~/.kube/
    state: directory

- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes

- name: Reset k8s
  shell: "kubeadm reset -f --cri-socket {{ runtime[k8s.runtime].cri.socket }}"

- name: Install helm (1/2)
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0555'

- name: Install helm (2/2)
  ansible.builtin.shell: "/tmp/get_helm.sh"

- name: Install Helm spray plugin
  kubernetes.core.helm_plugin:
    plugin_version: '{{ helm_spray }}'
    plugin_path: https://github.com/ThalesGroup/helm-spray
    state: present
