{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: iperf-pod
data:
  script.sh: |
    #!/bin/bash
    timeout=120
    until ping -c 1 {{ .Values.config.upfIpadd }}; do
        if [[ $timeout -lt 0 ]]; then
            ifconfig
            error "Timed out waiting for interface upf to start"
        fi
        timeout=$((timeout - 1))
        sleep 1
    done    
    UPF_IP_ADD=$(getent hosts {{ .Values.config.upfIpadd }} | awk '{print $1}');
    UPF_IP_ADD=$(if [[ $UPF_IP_ADD ]]; then echo $UPF_IP_ADD; else echo {{ .Values.config.upfIpadd }};fi);
    ip route add {{ .Values.config.ueroute }} via $UPF_IP_ADD dev {{ .Values.config.routeInterface }}
    num_servers={{ .Values.config.noOfIperf3Server }}
    base_port=5200
    # Run iperf multiple times
    for i in `seq 1 $num_servers`; do

      # Set server port
      server_port=$(($base_port+$i));

      # Report file includes server port
      report_file=iperf3-${server_port}.txt

      # Run iperf
      iperf3 -s --daemon -p $server_port
    done
    /bin/bash -c 'trap : TERM INT; sleep infinity & wait'
{{- end }}
