- name: Create a certificate key
  shell: 'kubeadm certs certificate-key | tee certificate-key.pass'
  register: kubeadm_certificate_key

- name: Create kubeadm configuration
  ansible.builtin.template:
    src: kubeadm_config.yaml.j2
    dest: ./kubeadm_config.yaml
  vars:
    - certificate_key: '{{ kubeadm_certificate_key.stdout_lines[0] }}'

- name: Initialize the master node
  shell: 'kubeadm init --upload-certs --config kubeadm_config.yaml'
  register: kubeadm_init
  
- name: Create a symbolic link /etc/kubernetes/admin.conf -> ~/.kube/config
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Create tigera-operator namespace 
  kubernetes.core.k8s:
    name: tigera-operator
    api_version: v1
    kind: Namespace
    state: present

- name: Set Calico installation instructions
  ansible.builtin.template:
    src: tigera_operator.yaml.j2
    dest: tigera_operator.yaml

- name: Register project-calico helm repo
  shell: 'helm repo add projectcalico https://projectcalico.docs.tigera.io/charts'

- name: Install Calico
  shell: 'helm install calico projectcalico/tigera-operator --version v3.24.1 -f tigera_operator.yaml --namespace tigera-operator'

- name: Retrieve multus
  ansible.builtin.git:
    repo: https://github.com/k8snetworkplumbingwg/multus-cni.git
    dest: multus-cni
    version: v4.0.1
    force: yes

- name: Install multus
  kubernetes.core.k8s:
    state: present
    src: multus-cni/deployments/multus-daemonset.yml

- name: Install Node Feature Discovery
  shell: kubectl apply -k https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.15.4
