---
# k8s config
k8s:
  runtime: docker
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
  dnsDomain: cluster.local
  #apiserver_advertise_address: 172.16.2.27
  calico:
    #nodeAddressAutodetectionV4:
    #  cidrs:
    #    - 172.16.0.0/12
    #    #- 192.0.2.0/24
  encapsulation: VXLAN
# 5G config
GCN:
  namespace: pepr-ran-inria
  RAN:
    present: true
    custom_values: blueprint/pepr/oai-5g-ran-inria
    split:
      f1: true
      e1: true
  UE:
    present: false
    custom_values: blueprint/v2.0.1_pepr/oai-5g-ran-inria
    tests:
      landmark_ping:
        landmark: 12.1.1.1
