---
# k8s config
k8s:
  runtime: docker
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
  dnsDomain: cluster.local
  #controlPlaneEndpoint: 10.0.1.4:6443
  #apiserver_advertise_address: 192.0.2.1
  calico:
    # nodeAddressAutodetectionV4:
    #   cidrs:
    #     - 192.0.2.0/24
  encapsulation: VXLAN
# 5G config
GCN:
  namespace: blueprint
  core:
    present: true
  RAN:
    present: true
  UE:
    present: true
    tests:
      landmark_ping:
          landmark: 12.1.1.1
