---
- name: Install dependencies for XP
  hosts: localhost
  connection: local 
  become: yes

  pre_tasks:
  - name: Install dependencies
    ansible.builtin.apt:
      pkg:
        - curl
        - gettext-base
        - rsync
        - unzip
        - git
      state: present
  roles:
  - diodonfrost.terraform
